// Testing git attributes merge rules asdsad
program WinCS;

uses
  SimpleShareMem,
  Dialogs,
  Controls,
  Forms,
  Messages,
  SysUtils,
  Winapi.Windows,
  cxLookAndFeels,
  System.UITypes,
  IBQuery in 'SharedUnits\NotInLibraryPathStuff\Units\IBQuery.pas',
  System.Math in 'SharedUnits\NotInLibraryPathStuff\Units\System.Math.pas',
  UOneInstance in 'SharedUnits\Units\UOneInstance.pas',
  memdset in 'SharedUnits\Classes\memdset.pas',
  AniImg in 'SharedUnits\Classes\AniImg.pas',
  UApplicationAutoUpdateUtils in 'SharedUnits\Units\UApplicationAutoUpdateUtils.pas',
  UBtnAuthorization in 'SharedUnits\Units\UBtnAuthorization.pas',
  UDmResources in 'SharedUnits\DataModules\UDmResources.pas' {DmResources: TDataModule},
  UIBUpdateSQL in 'SharedUnits\Classes\UIBUpdateSQL.pas',
  USngUserPrefs in 'SharedUnits\Classes\USngUserPrefs.pas',
  UFrameBase in 'SharedUnits\Frames\Base\UFrameBase.pas' {FrameBase: TFrame},
  UFrameDateSpan in 'SharedUnits\Frames\UFrameDateSpan.pas' {FrameDateSpan: TFrame},
  UFrameDualListBox in 'SharedUnits\Frames\UFrameDualListBox.pas' {FrameDualListBox: TFrame},
  UFrameLogo in 'SharedUnits\Frames\UFrameLogo.pas' {FrameLogo: TFrame},
  UFrameStatus in 'SharedUnits\Frames\UFrameStatus.pas' {FrameStatus: TFrame},
  UFrmActivateSecOptWzd in 'SharedUnits\Forms\UFrmActivateSecOptWzd.pas' {FrmActivateSecOptWzd},
  UFrmBackupWarning in 'SharedUnits\Forms\UFrmBackupWarning.pas',
  UFrmBase in 'SharedUnits\Forms\Base\UFrmBase.pas' {FrmBase},
  UFrmDatabaseLocation in 'SharedUnits\Forms\UFrmDatabaseLocation.pas',
  UFrmDefineViews in 'SharedUnits\Forms\UFrmDefineViews.pas' {UFrmDefineViews},
  UFrmDefineViewsViewSummary in 'SharedUnits\Forms\UFrmDefineViewsViewSummary.pas' {UFrmDefineViewsViewSummary},
  UFrmDefineViewsFields in 'SharedUnits\Forms\UFrmDefineViewsFields.pas' {UFrmDefineViewsFields},
  UFrmDefineViewsMisc in 'SharedUnits\Forms\UFrmDefineViewsMisc.pas' {UFrmDefineViewsMisc},
  UFrmExit in 'SharedUnits\Forms\UFrmExit.pas' {FrmExit},
  UFrmExportDialog in 'SharedUnits\Forms\UFrmExportDialog.pas' {UFrmExportDialog},
  UXLSReadWriteGridExport in 'SharedUnits\Units\UXLSReadWriteGridExport.pas',
  UFrmLogin in 'SharedUnits\Forms\UFrmLogin.pas',
  UFrmLookup in 'SharedUnits\Forms\Base\UFrmLookup.pas' {FrmLookup},
  UFrmLowSQLQuery in 'SharedUnits\Forms\UFrmLowSQLQuery.pas' {FrmLowSQLQuery},
  UFrmLowSQLQueryParameters in 'SharedUnits\Forms\UFrmLowSQLQueryParameters.pas' {UFrmLowSQLQueryParameters},
  UFrmMaintenance in 'SharedUnits\Forms\Base\UFrmMaintenance.pas' {FrmMaintenance},
  UFrmMaintenancePageControl in 'SharedUnits\Forms\Base\UFrmMaintenancePageControl.pas' {FrmMaintenancePageControl},
  UFrmPreferences in 'SharedUnits\Forms\UFrmPreferences.pas' {FrmPreferences},
  UFrmPrintOptions in 'SharedUnits\Forms\UFrmPrintOptions.pas' {UFrmPrintOptions},
  UFrmPrintStatus in 'SharedUnits\Forms\UFrmPrintStatus.pas' {UFrmPrintStatus},
  UFrmRptViewer in 'SharedUnits\Forms\UFrmRptViewer.pas' {UFrmRptViewer},
  UFrmSecLoginOptMaint in 'SharedUnits\Forms\UFrmSecLoginOptMaint.pas',
  UFrmSecurityAuditHistoryLookup in 'SharedUnits\Forms\UFrmSecurityAuditHistoryLookup.pas',
  UFrmSecurityAuditHistoryWizard in 'SharedUnits\Forms\UFrmSecurityAuditHistoryWizard.pas',
  UFrmSecurityChangePassword in 'SharedUnits\Forms\UFrmSecurityChangePassword.pas',
  UFrmSecurityGroupsLookup in 'SharedUnits\Forms\UFrmSecurityGroupsLookup.pas' {UFrmSecurityGroupsLookup},
  UFrmSecurityGroupUserMaint in 'SharedUnits\Forms\UFrmSecurityGroupUserMaint.pas',
  UFrmSecurityLoggedInUsers in 'SharedUnits\Forms\UFrmSecurityLoggedInUsers.pas' {FrmSecurityLoggedInUsers},
  UFrmSecurityMaintenance in 'SharedUnits\Forms\UFrmSecurityMaintenance.pas',
  UFrmSecurityUsersLookup in 'SharedUnits\Forms\UFrmSecurityUsersLookup.pas',
  UFrmShowText in 'SharedUnits\Forms\UFrmShowText.pas' {FrmShowText},
  UFrmSoftwareUpdateExitApp in 'SharedUnits\Forms\UFrmSoftwareUpdateExitApp.pas' {UFrmSoftwareUpdateExitApp},
  UFrmSplashAbout in 'SharedUnits\Forms\UFrmSplashAbout.pas',
  UFrmViewName in 'SharedUnits\Forms\UFrmViewName.pas' {UFrmViewName},
  UFrmWindows in 'SharedUnits\Forms\UFrmWindows.pas' {FrmWindows},
  ULowConstants in 'SharedUnits\Units\ULowConstants.pas',
  ULowExceptions in 'SharedUnits\Classes\ULowExceptions.pas',
  ULowCxGridViewsManagement in 'SharedUnits\Classes\ULowCxGridViewsManagement.pas',
  ULowDevExBarsUtils in 'SharedUnits\Units\ULowDevExBarsUtils.pas',
  ULowEmptyComboBox in 'SharedUnits\Units\ULowEmptyComboBox.pas',
  ULowValidations in 'SharedUnits\Units\ULowValidations.pas',
  ULowWPDFUtils in 'SharedUnits\Units\ULowWPDFUtils.pas',
  UObjEntryInformation in 'SharedUnits\Classes\UObjEntryInformation.PAS',
  UObjGridViewCriteria in 'SharedUnits\Classes\UObjGridViewCriteria.pas',
  UObjSecurityAuditHistory in 'SharedUnits\Classes\UObjSecurityAuditHistory.pas',
  UObjSecurityRoutines in 'SharedUnits\Classes\UObjSecurityRoutines.pas',
  UObjSecUsers in 'SharedUnits\Classes\UObjSecUsers.pas',
  URptBase in 'SharedUnits\Reports\Base\URptBase.pas' {RptBase},
  USngDataAccess in 'SharedUnits\Classes\USngDataAccess.pas',
  UApplicationEvents in 'UApplicationEvents.pas',
  UFrmAdvanceCollBegBalLkp in 'forms\UFrmAdvanceCollBegBalLkp.pas' {FrmAdvanceCollBegBalLkp},
  UFrmAdvanceCollDetailLookup in 'forms\UFrmAdvanceCollDetailLookup.pas' {FrmAdvanceCollDetailLookup},
  UFrmAdvanceDrawBegBalLkp in 'forms\UFrmAdvanceDrawBegBalLkp.pas' {FrmAdvanceDrawBegBalLkp},
  UFrmAdvanceDrawDetailLookup in 'forms\UFrmAdvanceDrawDetailLookup.pas' {FrmAdvanceDrawDetailLookup},
  UFrmAnalysisOfCashBegBalLkp in 'forms\UFrmAnalysisOfCashBegBalLkp.pas' {FrmAnalysisOfCashBegBalLkp},
  UFrmAnalysisOfCashDetailLookup in 'forms\UFrmAnalysisOfCashDetailLookup.pas' {FrmAnalysisOfCashDetailLookup},
  UFrmBeginningBalanceMaint in 'forms\UFrmBeginningBalanceMaint.pas' {FrmBeginningBalanceMaint},
  UFrmCashDrawerBegBalLkp in 'forms\UFrmCashDrawerBegBalLkp.pas' {FrmCashDrawerBegBalLkp},
  UFrmCashOnHandClosingDetail in 'forms\UFrmCashOnHandClosingDetail.pas' {FrmCashOnHandClosingDetail},
  UFrmCollectionsBegBalLookup in 'forms\UFrmCollectionsBegBalLookup.pas' {FrmCollectionsBegBalLookup},
  UFrmCollectionsDetailLookup in 'forms\UFrmCollectionsDetailLookup.pas' {FrmCollectionsDetailLookup},
  UFrmDailyEntryMaint in 'forms\UFrmDailyEntryMaint.pas' {FrmDailyEntryMaint},
  UFrmDepositoriesBegBalLookup in 'forms\UFrmDepositoriesBegBalLookup.pas' {FrmDepositoriesBegBalLookup},
  UFrmDepositoriesDetailLookup in 'forms\UFrmDepositoriesDetailLookup.pas' {FrmDepositoriesDetailLookup},
  UFrmDepositoriesLkp in 'forms\UFrmDepositoriesLkp.pas' {FrmDepositoriesLkp},
  UFrmDepositoriesMaint in 'forms\UFrmDepositoriesMaint.pas' {FrmDepositoriesMaint},
  UFrmFinalizeWzd in 'forms\UFrmFinalizeWzd.pas' {FrmFinalizeWzd},
  UFrmFundsLedgerCashBegBalLkp in 'forms\UFrmFundsLedgerCashBegBalLkp.pas' {FrmFundsLedgerCashBegBalLkp},
  UFrmFundsLedgerCashDetailLookup in 'forms\UFrmFundsLedgerCashDetailLookup.pas' {FrmFundsLedgerCashDetailLookup},
  UFrmFundsLedgerInvBegBalLkp in 'forms\UFrmFundsLedgerInvBegBalLkp.pas' {FrmFundsLedgerInvBegBalLkp},
  UFrmInvDepositoriesLkp in 'forms\UFrmInvDepositoriesLkp.pas' {FrmInvDepositoriesLkp},
  UFrmInvDepositoriesMaint in 'forms\UFrmInvDepositoriesMaint.pas' {FrmInvDepositoriesMaint},
  UFrmInvestmentsBegBalLookup in 'forms\UFrmInvestmentsBegBalLookup.pas' {FrmInvestmentsBegBalLookup},
  UFrmInvestmentsDetailLookup in 'forms\UFrmInvestmentsDetailLookup.pas' {FrmInvestmentsDetailLookup},
  UFrmMainMenu in 'forms\UFrmMainMenu.pas' {FrmMainMenu},
  UFrmNotesLookup in 'forms\UFrmNotesLookup.pas' {FrmNotesLookup},
  UFrmOtherSourcesBegBalLookup in 'forms\UFrmOtherSourcesBegBalLookup.pas' {FrmOtherSourcesBegBalLookup},
  UFrmOtherSourcesDetailLookup in 'forms\UFrmOtherSourcesDetailLookup.pas' {FrmOtherSourcesDetailLookup},
  UFrmOtherSourcesLkp in 'forms\UFrmOtherSourcesLkp.pas' {FrmOtherSourcesLkp},
  UFrmOtherSourcesMaint in 'forms\UFrmOtherSourcesMaint.pas' {FrmOtherSourcesMaint},
  UFrmRptDest in 'SharedUnits\Forms\UFrmRptDest.pas' {UFrmRptDest},
  UFrmRptStatus in 'SharedUnits\Forms\UFrmRptStatus.pas' {UFrmRptStatus},
  UFrmSecLocationLookup in 'SharedUnits\Forms\UFrmSecLocationLookup.pas' {FrmSecLocationLookup},
  UFrmSecLocationMaint in 'SharedUnits\Forms\UFrmSecLocationMaint.pas' {FrmSecLocationMaint},
  UFrmSecLogLookup in 'SharedUnits\Forms\UFrmSecLogLookup.pas' {UFrmSecLogLookup},
  UFrmSecLogPurgeDate in 'SharedUnits\Forms\UFrmSecLogPurgeDate.pas' {UFrmSecLogPurgeDate},
  UFrmSecOptCkOutLookup in 'SharedUnits\Forms\UFrmSecOptCkOutLookup.pas' {UFrmSecOptCkOutLookup},
  UFrmSecOverridesLookup in 'SharedUnits\Forms\UFrmSecOverridesLookup.pas' {UFrmSecOverridesLookup},
  UFrmSecOverridesMaint in 'SharedUnits\Forms\UFrmSecOverridesMaint.pas' {UFrmSecOverridesMaint},
  UFrmSpecsMaint in 'forms\UFrmSpecsMaint.pas' {FrmSpecsMaint},
  UFrmSupportToolsPassword in 'SharedUnits\Forms\UFrmSupportToolsPassword.pas' {UFrmSupportToolsPassword},
  UMenuControl in 'UMenuControl.pas',
  UObjAdvanceDrawBegBal in 'classes\UObjAdvanceDrawBegBal.pas',
  UObjAdvanceDrawDetail in 'classes\UObjAdvanceDrawDetail.pas',
  UObjAnalysisOfCashBegBal in 'classes\UObjAnalysisOfCashBegBal.pas',
  UObjAnalysisOfCashDetail in 'classes\UObjAnalysisOfCashDetail.pas',
  UObjBalanceSheet in 'classes\UObjBalanceSheet.pas',
  UObjCashDrawerBegBal in 'classes\UObjCashDrawerBegBal.pas',
  UObjCkMinSysRequirments in 'SharedUnits\Classes\UObjCkMinSysRequirments.pas',
  UObjDCSSpecs in 'classes\UObjDCSSpecs.pas',
  UObjDepositories in 'classes\UObjDepositories.pas',
  UObjDepositoriesBegBal in 'classes\UObjDepositoriesBegBal.pas',
  UObjFundsLedgerCashBegBal in 'classes\UObjFundsLedgerCashBegBal.pas',
  UObjFundsLedgerCashDetail in 'classes\UObjFundsLedgerCashDetail.pas',
  UObjFundsLedgerInvBegBal in 'classes\UObjFundsLedgerInvBegBal.pas',
  UObjFundsLedgerInvDetail in 'classes\UObjFundsLedgerInvDetail.pas',
  UObjInvDepositories in 'classes\UObjInvDepositories.pas',
  UObjInvestmentsBegBal in 'classes\UObjInvestmentsBegBal.pas',
  UObjInvestmentsDetail in 'classes\UObjInvestmentsDetail.pas',
  UObjOtherSources in 'classes\UObjOtherSources.pas',
  UObjOtherSourcesBegBal in 'classes\UObjOtherSourcesBegBal.pas',
  UObjTaxCollections in 'classes\UObjTaxCollections.pas',
  UObjTaxCollectionsBegBal in 'classes\UObjTaxCollectionsBegBal.pas',
  URptCashDepositBal in 'reports\URptCashDepositBal.pas' {RptCashDepositBal},
  URptSecProfile in 'SharedUnits\reports\URptSecProfile.pas' {URptSecProfile},
  UFrmNotesByDateSpan in 'forms\UFrmNotesByDateSpan.pas' {FrmNotesByDateSpan},
  UObjReportMessage in 'classes\UObjReportMessage.pas',
  UFrmReportMsgLookup in 'forms\UFrmReportMsgLookup.pas' {FrmReportMsgLookup},
  UFrmReportMsgMaint in 'forms\UFrmReportMsgMaint.pas' {FrmReportMsgMaint},
  UObjApplicationEvents in 'SharedUnits\Classes\UObjApplicationEvents.pas',
  ULowPerformance in 'SharedUnits\Units\ULowPerformance.pas',
  UDebugSettings in 'SharedUnits\Classes\UDebugSettings.pas',
  UObjApplicationSecurity in 'SharedUnits\Classes\UObjApplicationSecurity.pas',
  UFrmSecurityLoggedInUsersForceLogout in 'SharedUnits\Forms\UFrmSecurityLoggedInUsersForceLogout.pas' {FrmSecurityLoggedInUsersForceLogout},
  UObjCountyData in 'classes\UObjCountyData.pas',
  UFrmChangeCurBusinessDate in 'forms\UFrmChangeCurBusinessDate.pas' {FrmChangeCurBusinessDate},
  UObjTaxUnit in 'classes\UObjTaxUnit.pas',
  UFrmTaxUnitsLookup in 'forms\UFrmTaxUnitsLookup.pas' {FrmTaxUnitsLookup},
  UFrmTaxUnitMaint in 'forms\UFrmTaxUnitMaint.pas' {FrmTaxUnitMaint},
  UFrmSecurityLoggedInUserForceSelfLogout in 'SharedUnits\Forms\UFrmSecurityLoggedInUserForceSelfLogout.pas' {FrmSecurityLoggedInUserForceSelfLogout},
  UObjTax_TaxCollections in 'classes\UObjTax_TaxCollections.pas',
  UObjTax_TaxUnits in 'classes\UObjTax_TaxUnits.pas',
  UObjTaxUnitsCrosswalk in 'classes\UObjTaxUnitsCrosswalk.pas',
  UFrmTax_TaxCollections in 'forms\UFrmTax_TaxCollections.pas' {FrmTax_TaxCollections},
  UFrmWizard in 'SharedUnits\Forms\Base\UFrmWizard.pas' {FrmWizard},
  UFrmImportFromTaxWzd in 'forms\UFrmImportFromTaxWzd.pas' {FrmImportFromTaxWzd},
  UFrmTaxUnitsCrosswalkMaint in 'forms\UFrmTaxUnitsCrosswalkMaint.pas' {FrmTaxUnitsCrosswalkMaint},
  UObjGridView in 'SharedUnits\Classes\UObjGridView.pas',
  UObjNoBackupLogs in 'SharedUnits\Classes\UObjNoBackupLogs.pas',
  UObjProcessLogs in 'SharedUnits\Classes\UObjProcessLogs.pas',
  UObjSQLLog in 'SharedUnits\Classes\UObjSQLLog.pas',
  UFrmLogsViewer in 'SharedUnits\Forms\UFrmLogsViewer.pas' {FrmLogsViewer},
  UFrmNoBackupLogsLookup in 'SharedUnits\Forms\UFrmNoBackupLogsLookup.pas' {FrmNoBackupLogs},
  UFrmProcessLogsLookup in 'SharedUnits\Forms\UFrmProcessLogsLookup.pas' {FrmProcessLogsLookup},
  UFrmProcessLogsMaint in 'SharedUnits\Forms\UFrmProcessLogsMaint.pas' {FrmProcessLogsMaint},
  UFrmSQLLogLookup in 'SharedUnits\Forms\UFrmSQLLogLookup.pas' {FrmSQLLogLookup},
  UObjTax_SettlementData in 'classes\UObjTax_SettlementData.pas',
  UFrmTax_SettlementData in 'forms\UFrmTax_SettlementData.pas' {FrmTax_SettlementData},
  UFrmMaintenanceEntryInfo in 'SharedUnits\Forms\Base\UFrmMaintenanceEntryInfo.pas' {FrmMaintenanceEntryInfo},
  UFrmCopyFileConfirm in 'SharedUnits\Forms\UFrmCopyFileConfirm.pas' {FrmCopyFileConfirm},
  UFrmExportLocation in 'SharedUnits\Forms\UFrmExportLocation.pas' {FrmExportLocation},
  UFrmLogSQLSteps in 'SharedUnits\Forms\UFrmLogSQLSteps.pas' {FrmLogSQLSteps},
  UFrameSelectDirectory in 'SharedUnits\Frames\UFrameSelectDirectory.pas' {FrameSelectDirectory: TFrame},
  UFrmLowMessageDlg in 'SharedUnits\Forms\UFrmLowMessageDlg.pas' {FrmLowMessageDlg},
  UObjViewUserMachineSpecs in 'SharedUnits\Classes\UObjViewUserMachineSpecs.pas',
  UFrmViewUserMachineSpecsDeleteByDate in 'SharedUnits\Forms\UFrmViewUserMachineSpecsDeleteByDate.pas' {FrmViewUserMachineSpecsDeleteByDate},
  UFrmViewUserMachineSpecsLkp in 'SharedUnits\Forms\UFrmViewUserMachineSpecsLkp.pas' {FrmViewUserMachineSpecsLkp},
  UFrmViewUserMachineSpecsMaint in 'SharedUnits\Forms\UFrmViewUserMachineSpecsMaint.pas' {FrmViewUserMachineSpecsMaint},
  ULowHelper in 'SharedUnits\Units\ULowHelper.pas',
  ULowWindowsMessages in 'SharedUnits\Units\ULowWindowsMessages.pas',
  UApplicationSingleton in 'SharedUnits\Classes\UApplicationSingleton.pas',
  UFrmAddRemoveSecOptions in 'SharedUnits\Forms\UFrmAddRemoveSecOptions.pas' {FrmAddRemoveSecOptions},
  UFrmShowDataDialog in 'SharedUnits\Forms\UFrmShowDataDialog.pas' {FrmShowDataDialog},
  UFrmViewSecurityOptions in 'SharedUnits\Forms\UFrmViewSecurityOptions.pas',
  UObjLst in 'SharedUnits\Classes\UObjLst.PAS',
  UObjSave in 'SharedUnits\Classes\UObjSave.pas',
  UObjSecGroup in 'SharedUnits\Classes\UObjSecGroup.pas',
  UObjSecLocation in 'SharedUnits\Classes\UObjSecLocation.pas',
  UObjSecLogFile in 'SharedUnits\Classes\UObjSecLogFile.pas',
  UObjSecOptions in 'SharedUnits\Classes\UObjSecOptions.pas',
  UObjSecRights in 'SharedUnits\Classes\UObjSecRights.pas',
  UObjSystemInfo in 'SharedUnits\Classes\UObjSystemInfo.pas',
  ULowInterfaces in 'SharedUnits\Units\ULowInterfaces.pas',
  UEncryptionUtils in 'SharedUnits\Units\UEncryptionUtils.pas',
  UObjTempTable in 'SharedUnits\Classes\UObjTempTable.pas',
  UObjTempTableAccess in 'SharedUnits\Classes\UObjTempTableAccess.pas',
  ULowInterfacesForms in 'SharedUnits\Units\ULowInterfacesForms.pas',
  ULowFormUtils in 'SharedUnits\Units\ULowFormUtils.pas',
  UFrmRestoreDefaults in 'SharedUnits\Forms\UFrmRestoreDefaults.pas' {FrmRestoreDefaults},
  ULowDBUtils in 'SharedUnits\Units\ULowDBUtils.pas',
  UObjTempTableGlobal in 'SharedUnits\Classes\UObjTempTableGlobal.pas',
  UGlobalTempTableAccessSingleton in 'SharedUnits\Classes\UGlobalTempTableAccessSingleton.pas',
  ULowIBMetaData in 'SharedUnits\Units\ULowIBMetaData.pas',
  UCustomEditRepositoryItems in 'SharedUnits\Units\UCustomEditRepositoryItems.pas',
  UObjArchivedReports in 'SharedUnits\Classes\UObjArchivedReports.pas',
  UObjArchivedReportsSpecs in 'SharedUnits\Classes\UObjArchivedReportsSpecs.pas',
  UObjArchivedReportTypes in 'SharedUnits\Classes\UObjArchivedReportTypes.pas',
  UFrmViewArchivedReports in 'SharedUnits\Forms\UFrmViewArchivedReports.pas' {FrmViewArchivedReports},
  UFrmViewArchivedReportsLkp in 'SharedUnits\Forms\UFrmViewArchivedReportsLkp.pas' {FrmViewArchivedReportsLkp},
  UObjRanges in 'SharedUnits\Classes\UObjRanges.pas',
  UFramePageSelection in 'SharedUnits\Frames\UFramePageSelection.pas' {FramePageSelection: TFrame},
  UFrmPageSelection in 'SharedUnits\Forms\UFrmPageSelection.pas' {FrmPageSelection},
  ULowSetterHelper in 'SharedUnits\Classes\ULowSetterHelper.pas',
  ULowTypeHelpers in 'SharedUnits\Units\ULowTypeHelpers.pas',
  ULowValidationHelper in 'SharedUnits\Classes\ULowValidationHelper.pas',
  UObjAddRemoveSecOptions in 'SharedUnits\Classes\UObjAddRemoveSecOptions.pas',
  ULowTypeHelpersForms in 'SharedUnits\Units\ULowTypeHelpersForms.pas',
  UFrameRptType in 'SharedUnits\Frames\UFrameRptType.pas' {FrameRptType: TFrame},
  UFrmRptWizard in 'SharedUnits\Forms\Base\UFrmRptWizard.pas' {FrmRptWizard},
  UFrmCashDepositBalRptWzd in 'forms\UFrmCashDepositBalRptWzd.pas' {FrmCashDepositBalRptWzd},
  UFrmProgress in 'SharedUnits\Forms\UFrmProgress.pas' {FrmProgress},
  UFrameProgressBar in 'SharedUnits\Frames\UFrameProgressBar.pas' {FrameProgressBar: TFrame},
  UExecuteProcess in 'SharedUnits\Classes\UExecuteProcess.pas',
  UFormatMsgs in 'SharedUnits\Classes\UFormatMsgs.pas',
  UObjProgressBarController in 'SharedUnits\Classes\UObjProgressBarController.pas',
  UProgressCollection in 'SharedUnits\Classes\UProgressCollection.pas',
  UProgressDbLog in 'SharedUnits\Classes\UProgressDbLog.pas',
  UProgressFileLog in 'SharedUnits\Classes\UProgressFileLog.pas',
  UProgressSync in 'SharedUnits\Classes\UProgressSync.pas',
  UTerminate in 'SharedUnits\Classes\UTerminate.pas',
  UFrmSecProfileRptWzd in 'SharedUnits\Forms\UFrmSecProfileRptWzd.pas' {FrmSecProfileRptWzd},
  ULowSysUtils in 'SharedUnits\Units\ULowSysUtils.pas',
  ULowSimpleTypes in 'SharedUnits\Units\ULowSimpleTypes.pas',
  UConstants in 'UConstants.pas',
  UInterfaces in 'UInterfaces.pas',
  UObjEntrySpecs in 'classes\UObjEntrySpecs.pas',
  ULowDevExGridUtils in 'SharedUnits\Units\ULowDevExGridUtils.pas',
  ULowGridViewStorage in 'SharedUnits\Classes\ULowGridViewStorage.pas',
  ULowMessageDlg in 'SharedUnits\Units\ULowMessageDlg.pas',
  ULowAuthenticationUtils in 'SharedUnits\Units\ULowAuthenticationUtils.pas',
  ULowEncryptionUtils in 'SharedUnits\Units\ULowEncryptionUtils.pas',
  USelectionLimitsGTT in 'SharedUnits\Units\USelectionLimitsGTT.pas',
  UMdAdvanceCollBegBal in 'classes\UMdAdvanceCollBegBal.pas',
  UMdAdvanceCollDetail in 'classes\UMdAdvanceCollDetail.pas',
  UMdDepositoriesDetail in 'classes\UMdDepositoriesDetail.pas',
  UMdCashOnHandClosing in 'classes\UMdCashOnHandClosing.pas',
  UMdCashOnHandClosingDetail in 'classes\UMdCashOnHandClosingDetail.pas',
  UMdOtherSourcesDetail in 'classes\UMdOtherSourcesDetail.pas',
  ULowSingleton in 'SharedUnits\Units\ULowSingleton.pas',
  UThreadSafe in 'SharedUnits\Classes\UThreadSafe.pas',
  UThreadSafeCollections in 'SharedUnits\Classes\UThreadSafeCollections.pas',
  UObjParamStore in 'SharedUnits\Classes\UObjParamStore.pas',
  UMdNotes in 'classes\UMdNotes.pas',
  ULowCxGridViewManagementJSON in 'SharedUnits\Classes\ULowCxGridViewManagementJSON.pas',
  ULowJSON in 'SharedUnits\Classes\ULowJSON.pas',
  UFrameCbxBase in 'SharedUnits\Frames\Base\UFrameCbxBase.pas' {FrameCbxBase: TFrame},
  UFrameCbx in 'SharedUnits\Frames\UFrameCbx.pas' {FrameCbx: TFrame},
  UFrameCbxDB in 'SharedUnits\Frames\UFrameCbxDB.pas' {FrameCbxDB: TFrame},
  ULowInitApp in 'units\ULowInitApp.pas',
  ULowFormSettings in 'SharedUnits\Units\ULowFormSettings.pas',
  ULowInitializeApp in 'SharedUnits\Units\ULowInitializeApp.pas',
  ULowInitCustApp in 'SharedUnits\Classes\ULowInitCustApp.pas',
  UObjCmdLineExec in 'SharedUnits\Classes\UObjCmdLineExec.pas',
  UIBDataAccess in 'SharedUnits\Classes\UIBDataAccess.pas',
  UMDManualDBLog in 'SharedUnits\Classes\UMDManualDBLog.pas',
  UFrameComponent in 'SharedUnits\Frames\UFrameComponent.pas' {FrameComponent: TFrame},
  UFrameGridDefault in 'SharedUnits\Frames\UFrameGridDefault.pas' {FrameGridDefault: TFrame},
  UFrameGrid in 'SharedUnits\Frames\UFrameGrid.pas' {FrameGrid: TFrame},
  UPrinting in 'SharedUnits\Classes\UPrinting.pas',
  ULowDataSetUtils in 'SharedUnits\Units\ULowDataSetUtils.pas',
  UBusy in 'SharedUnits\Classes\UBusy.pas',
  ULowDeltaHandlerDB in 'SharedUnits\Classes\ULowDeltaHandlerDB.pas',
  UMdMfaSession in 'SharedUnits\Classes\UMdMfaSession.pas',
  UMdMfaSessionDuration in 'SharedUnits\Classes\UMdMfaSessionDuration.pas',
  UMfaUserInfo in 'SharedUnits\Classes\UMfaUserInfo.pas',
  UFrmTotpCredentials in 'SharedUnits\Forms\UFrmTotpCredentials.pas' {FrmTotpCredentials: TdxForm},
  ULowQRCode in 'SharedUnits\Units\ULowQRCode.pas';

{$R *.RES}


begin
  try
    try
      FLowInitApp := TLowInitApp.Create(lstCashSheet, 'CashSheet');
      Application.Initialize;
    except
      on e: Exception do
      begin
        Application.ProcessMessages;
        if not(e is ELowCancelException) then
        begin
          ShowMessage(Format(cMsgLowInitAppErr, [Application.Title, e.Message]));
        end;
      end;
    end;
  finally
    Application.ProcessMessages;
  end;

end.
